import 'package:icicles_animation_dart/icicles_animation_dart.dart';
import 'package:test/test.dart';

void main() {
  test('Animation - decode darkening file generated by js library', () async {
    final animation = Animation(
      'My Anim',
      xCount: 1,
      yCount: 1,
      radioPanelsCount: 2,
      radioPanelPixelCount: 10,
    );

    final icicles = Icicles(animation);
    expect(animation.frames, hasLength(0));

    icicles
      ..setAllPixelsColor(Colors.red)
      ..show(Duration(seconds: 1));

    expect(animation.frames, [
      isA<VisualFrame>(),
    ]);

    icicles
      ..setRadioPanelPixelColor(1, 0, Colors.red)
      ..setRadioPanelPixelColor(2, 1, Colors.red)
      ..setAllPixelsColor(Colors.green)
      ..show(Duration(seconds: 1));

    expect(animation.frames, [
      isA<VisualFrame>(),
      isA<RadioVisualFrame>(),
      isA<RadioVisualFrame>(),
      isA<VisualFrame>(),
    ]);

    // final readBytes = await File(animationFilePath).readAsBytes();
    // final encodedBytes = animation.toBytes();

    // expect(readBytes, orderedEquals(encodedBytes));
  });
}
