name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  equatable: ^2.0.5
  icicles_animation_dart:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
