name: icicles_animation_dart
description: Dart library for creating icicle animations.
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  meta: ^1.8.0
  path: ^1.8.2
