name: icicles_animation_dart
description: Dart library for creating icicle animations.
version: 3.0.0

environment:
  sdk: ^3.5.3

dependencies:
  collection: ^1.17.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
