name: icicles_animation_dart
description: Dart library for creating icicle animations.
version: 1.3.2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  meta: ^1.8.0

dev_dependencies:
  test: ^1.22.1
  pedantic: ^1.9.0
