name: icicles_animation_dart
description: Dart library for creating icicle animations.
version: 1.3.3

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  equatable: ^2.0.5
  meta: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
